const morphTargets = [
  "eyeBlinkLeft",
  "eyeBlinkRight",
  "jawOpen",
  "mouthSmileLeft",
  "mouthSmileRight",
  "browInnerUp",
  "browDownLeft",
  "browDownRight",
  "eyeSquintLeft",
  "eyeSquintRight",
  "noseSneerLeft",
  "noseSneerRight",
  "cheekPuff",
  "mouthFunnel",
  "mouthPucker",
  "mouthPressLeft",
  "mouthPressRight",
  "mouthShrugLower",
  "mouthDimpleLeft",
  "mouthDimpleRight",
  "mouthStretchLeft",
  "mouthStretchRight",
  "tongueOut",
];
export default morphTargets;
